.

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -109,6 +109,9 @@ stages:
           health_json=$(kubectl exec $POD -- curl -s http://localhost:5555/health)
           if [ -z "${health_json}" ]; then
             echo "Empty response to http://localhost:5555/health for pod ${POD}" && exit 1
+          else
+            echo "Health status for pod ${POD}"
+            echo ${health_json}
           fi
           status_checks=$(echo "$health_json" | jq '. | .. | .status? // empty | select(. != "UP")')
           if [[ -n "$status_checks" ]]; then
@@ -132,7 +135,7 @@ stages:
     steps:
 
     - script: |
-        AUTH_HEADER=$(echo "Administrator:${SAG_MSR_ADMIN_PASSWORD}" | base64)
+        AUTH_HEADER=$(echo -n "Administrator:${SAG_MSR_ADMIN_PASSWORD}" | base64)
         echo "##vso[task.setvariable variable=AUTH_HEADER]${AUTH_HEADER}"
       displayName: 'Set basic auth header'
       env:
@@ -141,13 +144,10 @@ stages:
     - script: |
         RESPONSE=$(curl -s --location --request POST 'https://msr-frontend.sttlab.eu/personnesAPI/personnes/demande-zip' \
           --header 'Authorization: Basic '${AUTH_HEADER})
-        echo "Response: \n${RESPONSE}"
+        echo "POST /personnes/demande-zip response:"
+        echo "${RESPONSE}"
         ID_DEMANDE=$(echo "${RESPONSE}" | jq -r '.idDemande')
-        echo "ID demande: \n${ID_DEMANDE}"
         if [ -z "${ID_DEMANDE}" ]; then
-          echo "POST /personnes/demande-zip --> ERROR (Invalid idDemande in response: ${ID_DEMANDE})"
-          curl -v --location --request POST 'https://msr-frontend.sttlab.eu/personnesAPI/personnes/demande-zip' \
-          --header 'Authorization: Basic '${AUTH_HEADER}
-          exit 1
+          echo "POST /personnes/demande-zip --> ERROR (Invalid idDemande in response: ${ID_DEMANDE})" && exit 1
         fi
       displayName: 'POST /personnes/demande-zip'      
